[tox]
envlist = py39, py310, py311, py312, py313, py314
isolated_build = True
skip_missing_interpreters = True

[testenv]
deps =
  pytest
  pytest-cov
  pytest-randomly
  pytest-xdist
  shtab==1.9.2
commands = pytest -m smoke -n=auto
