# Generated by tools/generate_shell_completions.py; do not edit bundled output.
# PowerShell 7+: register native completion without executing the input being completed.
& {
    $metadata = @'
__TTE_METADATA__
'@ | ConvertFrom-Json -AsHashtable
    $completer = {
        param($wordToComplete, $commandAst, $cursorPosition)
        $context = $metadata.root
        $pending = $null
        $count = 0
        $optionsEnded = $false
        $prefix = [string]$wordToComplete
        foreach ($element in @($commandAst.CommandElements | Select-Object -Skip 1)) {
            if ($element.Extent.StartOffset -ge $cursorPosition) { break }
            if ($element.Extent.EndOffset -ge $cursorPosition) { break }
            # Read literal AST values only. Never evaluate variables, subexpressions or script blocks.
            if ($element -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
                $token = $element.Value
            } elseif ($element -is [System.Management.Automation.Language.CommandParameterAst]) {
                $token = $element.Extent.Text
            } elseif ($element -is [System.Management.Automation.Language.ConstantExpressionAst]) {
                $token = [string]$element.Value
            } else { return }
            $optionName = ($token -split '=', 2)[0]
            $isOption = !$optionsEnded -and $context.options.ContainsKey($optionName)
            if ($pending -and !$isOption -and !($token -eq '--' -and $count -ge $pending.min)) {
                $count++
                if ($pending.max -ge 0 -and $count -ge $pending.max) { $pending = $null }
                continue
            }
            if ($pending -and $count -lt $pending.min) { return }
            $pending = $null
            if ($token -eq '--') { $optionsEnded = $true; continue }
            if ($isOption) {
                $option = $context.options[$optionName]
                $count = [int]($token.Contains('='))
                if ($option.max -ne 0 -and ($option.max -lt 0 -or $count -lt $option.max)) {
                    $pending = $option
                }
                continue
            }
            if ($context -eq $metadata.root -and $metadata.effects.ContainsKey($token)) {
                $context = $metadata.effects[$token]
                $optionsEnded = $false
            }
        }
        # Quotes are syntax, not part of a completion prefix. Do not expand their contents.
        if ($prefix.StartsWith("'") -or $prefix.StartsWith('"')) {
            $quote = $prefix.Substring(0, 1)
            $prefix = $prefix.Substring(1)
            if ($prefix.EndsWith($quote)) { $prefix = $prefix.Substring(0, $prefix.Length - 1) }
            if ($quote -eq "'") { $prefix = $prefix.Replace("''", "'") }
        }
        $assignment = ''
        if (!$optionsEnded -and $prefix.Contains('=')) {
            $parts = $prefix -split '=', 2
            if ($context.options.ContainsKey($parts[0])) {
                $pending = $context.options[$parts[0]]
                $assignment = $parts[0] + '='
                $prefix = $parts[1]
            }
        }
        if ($pending -and $pending.max -eq 0) { return }
        if ($pending -and !($prefix.StartsWith('-') -and $count -ge $pending.min -and !$assignment)) {
            if ($pending.file) {
                foreach ($result in [System.Management.Automation.CompletionCompleters]::CompleteFilename($prefix)) {
                    [System.Management.Automation.CompletionResult]::new(
                        $assignment + $result.CompletionText, $result.ListItemText, $result.ResultType, $result.ToolTip)
                }
                return
            }
            foreach ($value in $pending.choices) {
                if ([string]$value -and ([string]$value).StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
                    [System.Management.Automation.CompletionResult]::new(
                        $assignment + $value, $value, 'ParameterValue', $pending.help)
                }
            }
            return
        }
        if (!$optionsEnded) {
            foreach ($name in @($context.options.Keys | Sort-Object)) {
                if ($name.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
                    [System.Management.Automation.CompletionResult]::new(
                        $name, $name, 'ParameterName', $context.options[$name].help)
                }
            }
        }
        if ($context -eq $metadata.root) {
            foreach ($name in @($metadata.effects.Keys | Sort-Object)) {
                if ($name.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
                    [System.Management.Automation.CompletionResult]::new($name, $name, 'ParameterValue', $name)
                }
            }
        }
    }.GetNewClosure()
    Register-ArgumentCompleter -Native -CommandName tte, terminaltexteffects -ScriptBlock $completer
}
