# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab

_shtab_tte_subparsers=(beams binarypath blackhole bouncyballs bubbles burn colorshift crumble decrypt dev errorcorrect expand fireworks highlight laseretch matrix middleout orbittingvolley overflow pour print rain randomsequence rings scattered slice slide smoke spotlights spray swarm sweep synthgrid thunderstorm unstable vhstape waves wipe)

_shtab_tte_option_strings=(-h --help --input-file -i --version -v --print-completion --random-effect -R --seed --include-effects --exclude-effects --tab-width --xterm-colors --no-color --terminal-background-color --existing-color-handling --wrap-text --frame-rate --canvas-width --canvas-height --anchor-canvas --anchor-text --ignore-terminal-dimensions --reuse-canvas --no-eol --no-restore-cursor)
_shtab_tte_beams_option_strings=(-h --help --beam-row-symbols --beam-column-symbols --beam-delay --beam-row-speed-range --beam-column-speed-range --beam-gradient-stops --beam-gradient-steps --beam-gradient-frames --final-gradient-stops --final-gradient-steps --final-gradient-frames --final-gradient-direction --final-wipe-speed)
_shtab_tte_binarypath_option_strings=(-h --help --final-gradient-stops --final-gradient-steps --final-gradient-direction --binary-colors --movement-speed --active-binary-groups)
_shtab_tte_blackhole_option_strings=(-h --help --blackhole-color --star-colors --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_bouncyballs_option_strings=(-h --help --ball-colors --ball-symbols --ball-delay --movement-speed --movement-easing --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_bubbles_option_strings=(-h --help --rainbow --bubble-colors --pop-color --bubble-speed --bubble-delay --pop-condition --movement-easing --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_burn_option_strings=(-h --help --starting-color --burn-colors --smoke-chance --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_colorshift_option_strings=(-h --help --gradient-stops --gradient-steps --gradient-frames --no-travel --travel-direction --reverse-travel-direction --no-loop --cycles --skip-final-gradient --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_crumble_option_strings=(-h --help --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_decrypt_option_strings=(-h --help --typing-speed --ciphertext-colors --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_dev_option_strings=(-h --help --color-single --final-gradient-stops --final-gradient-steps --final-gradient-frames --final-gradient-direction --movement-speed --easing)
_shtab_tte_errorcorrect_option_strings=(-h --help --error-pairs --swap-delay --error-color --correct-color --movement-speed --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_expand_option_strings=(-h --help --expand-easing --movement-speed --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_fireworks_option_strings=(-h --help --explode-anywhere --firework-colors --firework-symbol --firework-volume --launch-delay --explode-distance --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_highlight_option_strings=(-h --help --highlight-brightness --highlight-direction --highlight-width --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_laseretch_option_strings=(-h --help --etch-pattern --etch-speed --etch-delay --cool-gradient-stops --laser-gradient-stops --spark-gradient-stops --spark-cooling-frames --final-gradient-stops --final-gradient-steps --final-gradient-frames --final-gradient-direction)
_shtab_tte_matrix_option_strings=(-h --help --highlight-color --rain-color-gradient --rain-symbols --rain-fall-delay-range --rain-column-delay-range --rain-time --symbol-swap-chance --color-swap-chance --resolve-delay --final-gradient-stops --final-gradient-steps --final-gradient-frames --final-gradient-direction)
_shtab_tte_middleout_option_strings=(-h --help --starting-color --expand-direction --center-movement-speed --full-movement-speed --center-easing --full-easing --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_orbittingvolley_option_strings=(-h --help --top-launcher-symbol --right-launcher-symbol --bottom-launcher-symbol --left-launcher-symbol --launcher-movement-speed --character-movement-speed --volley-size --launch-delay --character-easing --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_overflow_option_strings=(-h --help --overflow-gradient-stops --overflow-cycles-range --overflow-speed --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_pour_option_strings=(-h --help --pour-direction --pour-speed --movement-speed-range --gap --starting-color --final-gradient-stops --final-gradient-steps --final-gradient-frames --final-gradient-direction --movement-easing)
_shtab_tte_print_option_strings=(-h --help --print-head-return-speed --print-speed --print-head-easing --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_rain_option_strings=(-h --help --rain-colors --movement-speed --rain-symbols --final-gradient-stops --final-gradient-steps --final-gradient-direction --movement-easing)
_shtab_tte_randomsequence_option_strings=(-h --help --speed --final-gradient-stops --final-gradient-steps --final-gradient-frames --final-gradient-direction)
_shtab_tte_rings_option_strings=(-h --help --ring-colors --ring-gap --spin-duration --spin-speed --disperse-duration --spin-disperse-cycles --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_scattered_option_strings=(-h --help --movement-speed --movement-easing --final-gradient-stops --final-gradient-steps --final-gradient-frames --final-gradient-direction)
_shtab_tte_slice_option_strings=(-h --help --slice-direction --movement-speed --movement-easing --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_slide_option_strings=(-h --help --movement-speed --grouping --gap --reverse-direction --merge --movement-easing --final-gradient-stops --final-gradient-steps --final-gradient-frames --final-gradient-direction)
_shtab_tte_smoke_option_strings=(-h --help --starting-color --smoke-symbols --smoke-gradient-stops --use-whole-canvas --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_spotlights_option_strings=(-h --help --beam-width-ratio --beam-falloff --search-duration --search-speed-range --spotlight-count --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_spray_option_strings=(-h --help --spray-position --spray-volume --movement-speed-range --movement-easing --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_swarm_option_strings=(-h --help --base-color --flash-color --swarm-size --swarm-coordination --swarm-area-count-range --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_sweep_option_strings=(-h --help --sweep-symbols --first-sweep-direction --second-sweep-direction --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_synthgrid_option_strings=(-h --help --grid-gradient-stops --grid-gradient-steps --grid-gradient-direction --text-gradient-stops --text-gradient-steps --text-gradient-direction --grid-row-symbol --grid-column-symbol --text-generation-symbols --max-active-blocks)
_shtab_tte_thunderstorm_option_strings=(-h --help --lightning-color --glowing-text-color --text-glow-time --raindrop-symbols --spark-symbols --spark-glow-color --spark-glow-time --storm-time --final-gradient-stops --final-gradient-steps --final-gradient-frames --final-gradient-direction)
_shtab_tte_unstable_option_strings=(-h --help --unstable-color --explosion-ease --explosion-speed --reassembly-ease --reassembly-speed --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_vhstape_option_strings=(-h --help --glitch-line-colors --glitch-wave-colors --noise-colors --glitch-line-chance --noise-chance --total-glitch-time --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_waves_option_strings=(-h --help --wave-symbols --wave-gradient-stops --wave-gradient-steps --wave-count --wave-length --wave-direction --wave-easing --final-gradient-stops --final-gradient-steps --final-gradient-direction)
_shtab_tte_wipe_option_strings=(-h --help --wipe-direction --wipe-delay --wipe-ease --final-gradient-stops --final-gradient-steps --final-gradient-frames --final-gradient-direction)

_shtab_tte___input_file_COMPGEN=_shtab_compgen_files
_shtab_tte__i_COMPGEN=_shtab_compgen_files

_shtab_tte_pos_0_choices=(beams binarypath blackhole bouncyballs bubbles burn colorshift crumble decrypt dev errorcorrect expand fireworks highlight laseretch matrix middleout orbittingvolley overflow pour print rain randomsequence rings scattered slice slide smoke spotlights spray swarm sweep synthgrid thunderstorm unstable vhstape waves wipe)
_shtab_tte___print_completion_choices=(bash zsh)
_shtab_tte___include_effects_choices=(beams binarypath blackhole bouncyballs bubbles burn colorshift crumble decrypt dev errorcorrect expand fireworks highlight laseretch matrix middleout orbittingvolley overflow pour print rain randomsequence rings scattered slice slide smoke spotlights spray swarm sweep synthgrid thunderstorm unstable vhstape waves wipe)
_shtab_tte___exclude_effects_choices=(beams binarypath blackhole bouncyballs bubbles burn colorshift crumble decrypt dev errorcorrect expand fireworks highlight laseretch matrix middleout orbittingvolley overflow pour print rain randomsequence rings scattered slice slide smoke spotlights spray swarm sweep synthgrid thunderstorm unstable vhstape waves wipe)
_shtab_tte___existing_color_handling_choices=(always dynamic ignore)
_shtab_tte___anchor_canvas_choices=(sw s se e ne n nw w c)
_shtab_tte___anchor_text_choices=(n ne e se s sw w nw c)
_shtab_tte_bubbles___pop_condition_choices=(row bottom anywhere)
_shtab_tte_middleout___expand_direction_choices=(vertical horizontal)
_shtab_tte_pour___pour_direction_choices=(up down left right)
_shtab_tte_slice___slice_direction_choices=(vertical horizontal diagonal)
_shtab_tte_slide___grouping_choices=(row column diagonal)
_shtab_tte_spray___spray_position_choices=(n ne e se s sw w nw center)
_shtab_tte_waves___wave_direction_choices=(column_left_to_right column_right_to_left row_top_to_bottom row_bottom_to_top center_to_outside outside_to_center)

_shtab_tte_pos_0_nargs=A...
_shtab_tte__h_nargs=0
_shtab_tte___help_nargs=0
_shtab_tte___version_nargs=0
_shtab_tte__v_nargs=0
_shtab_tte___random_effect_nargs=0
_shtab_tte__R_nargs=0
_shtab_tte___include_effects_nargs=+
_shtab_tte___exclude_effects_nargs=+
_shtab_tte___xterm_colors_nargs=0
_shtab_tte___no_color_nargs=0
_shtab_tte___wrap_text_nargs=0
_shtab_tte___ignore_terminal_dimensions_nargs=0
_shtab_tte___reuse_canvas_nargs=0
_shtab_tte___no_eol_nargs=0
_shtab_tte___no_restore_cursor_nargs=0
_shtab_tte_beams__h_nargs=0
_shtab_tte_beams___help_nargs=0
_shtab_tte_beams___beam_row_symbols_nargs=+
_shtab_tte_beams___beam_column_symbols_nargs=+
_shtab_tte_beams___beam_gradient_stops_nargs=+
_shtab_tte_beams___beam_gradient_steps_nargs=+
_shtab_tte_beams___final_gradient_stops_nargs=+
_shtab_tte_beams___final_gradient_steps_nargs=+
_shtab_tte_binarypath__h_nargs=0
_shtab_tte_binarypath___help_nargs=0
_shtab_tte_binarypath___final_gradient_stops_nargs=+
_shtab_tte_binarypath___final_gradient_steps_nargs=+
_shtab_tte_binarypath___binary_colors_nargs=+
_shtab_tte_blackhole__h_nargs=0
_shtab_tte_blackhole___help_nargs=0
_shtab_tte_blackhole___star_colors_nargs=+
_shtab_tte_blackhole___final_gradient_stops_nargs=+
_shtab_tte_blackhole___final_gradient_steps_nargs=+
_shtab_tte_bouncyballs__h_nargs=0
_shtab_tte_bouncyballs___help_nargs=0
_shtab_tte_bouncyballs___ball_colors_nargs=+
_shtab_tte_bouncyballs___ball_symbols_nargs=+
_shtab_tte_bouncyballs___final_gradient_stops_nargs=+
_shtab_tte_bouncyballs___final_gradient_steps_nargs=+
_shtab_tte_bubbles__h_nargs=0
_shtab_tte_bubbles___help_nargs=0
_shtab_tte_bubbles___rainbow_nargs=0
_shtab_tte_bubbles___bubble_colors_nargs=+
_shtab_tte_bubbles___final_gradient_stops_nargs=+
_shtab_tte_bubbles___final_gradient_steps_nargs=+
_shtab_tte_burn__h_nargs=0
_shtab_tte_burn___help_nargs=0
_shtab_tte_burn___burn_colors_nargs=+
_shtab_tte_burn___final_gradient_stops_nargs=+
_shtab_tte_burn___final_gradient_steps_nargs=+
_shtab_tte_colorshift__h_nargs=0
_shtab_tte_colorshift___help_nargs=0
_shtab_tte_colorshift___gradient_stops_nargs=+
_shtab_tte_colorshift___gradient_steps_nargs=+
_shtab_tte_colorshift___no_travel_nargs=0
_shtab_tte_colorshift___reverse_travel_direction_nargs=0
_shtab_tte_colorshift___no_loop_nargs=0
_shtab_tte_colorshift___skip_final_gradient_nargs=0
_shtab_tte_colorshift___final_gradient_stops_nargs=+
_shtab_tte_colorshift___final_gradient_steps_nargs=+
_shtab_tte_crumble__h_nargs=0
_shtab_tte_crumble___help_nargs=0
_shtab_tte_crumble___final_gradient_stops_nargs=+
_shtab_tte_crumble___final_gradient_steps_nargs=+
_shtab_tte_decrypt__h_nargs=0
_shtab_tte_decrypt___help_nargs=0
_shtab_tte_decrypt___ciphertext_colors_nargs=+
_shtab_tte_decrypt___final_gradient_stops_nargs=+
_shtab_tte_decrypt___final_gradient_steps_nargs=+
_shtab_tte_dev__h_nargs=0
_shtab_tte_dev___help_nargs=0
_shtab_tte_dev___final_gradient_stops_nargs=+
_shtab_tte_dev___final_gradient_steps_nargs=+
_shtab_tte_errorcorrect__h_nargs=0
_shtab_tte_errorcorrect___help_nargs=0
_shtab_tte_errorcorrect___final_gradient_stops_nargs=+
_shtab_tte_errorcorrect___final_gradient_steps_nargs=+
_shtab_tte_expand__h_nargs=0
_shtab_tte_expand___help_nargs=0
_shtab_tte_expand___final_gradient_stops_nargs=+
_shtab_tte_expand___final_gradient_steps_nargs=+
_shtab_tte_fireworks__h_nargs=0
_shtab_tte_fireworks___help_nargs=0
_shtab_tte_fireworks___explode_anywhere_nargs=0
_shtab_tte_fireworks___firework_colors_nargs=+
_shtab_tte_fireworks___final_gradient_stops_nargs=+
_shtab_tte_fireworks___final_gradient_steps_nargs=+
_shtab_tte_highlight__h_nargs=0
_shtab_tte_highlight___help_nargs=0
_shtab_tte_highlight___final_gradient_stops_nargs=+
_shtab_tte_highlight___final_gradient_steps_nargs=+
_shtab_tte_laseretch__h_nargs=0
_shtab_tte_laseretch___help_nargs=0
_shtab_tte_laseretch___cool_gradient_stops_nargs=+
_shtab_tte_laseretch___laser_gradient_stops_nargs=+
_shtab_tte_laseretch___spark_gradient_stops_nargs=+
_shtab_tte_laseretch___final_gradient_stops_nargs=+
_shtab_tte_laseretch___final_gradient_steps_nargs=+
_shtab_tte_matrix__h_nargs=0
_shtab_tte_matrix___help_nargs=0
_shtab_tte_matrix___rain_color_gradient_nargs=+
_shtab_tte_matrix___rain_symbols_nargs=+
_shtab_tte_matrix___final_gradient_stops_nargs=+
_shtab_tte_matrix___final_gradient_steps_nargs=+
_shtab_tte_middleout__h_nargs=0
_shtab_tte_middleout___help_nargs=0
_shtab_tte_middleout___final_gradient_stops_nargs=+
_shtab_tte_middleout___final_gradient_steps_nargs=+
_shtab_tte_orbittingvolley__h_nargs=0
_shtab_tte_orbittingvolley___help_nargs=0
_shtab_tte_orbittingvolley___final_gradient_stops_nargs=+
_shtab_tte_orbittingvolley___final_gradient_steps_nargs=+
_shtab_tte_overflow__h_nargs=0
_shtab_tte_overflow___help_nargs=0
_shtab_tte_overflow___overflow_gradient_stops_nargs=+
_shtab_tte_overflow___final_gradient_stops_nargs=+
_shtab_tte_overflow___final_gradient_steps_nargs=+
_shtab_tte_pour__h_nargs=0
_shtab_tte_pour___help_nargs=0
_shtab_tte_pour___final_gradient_stops_nargs=+
_shtab_tte_pour___final_gradient_steps_nargs=+
_shtab_tte_print__h_nargs=0
_shtab_tte_print___help_nargs=0
_shtab_tte_print___final_gradient_stops_nargs=+
_shtab_tte_print___final_gradient_steps_nargs=+
_shtab_tte_rain__h_nargs=0
_shtab_tte_rain___help_nargs=0
_shtab_tte_rain___rain_colors_nargs=+
_shtab_tte_rain___rain_symbols_nargs=+
_shtab_tte_rain___final_gradient_stops_nargs=+
_shtab_tte_rain___final_gradient_steps_nargs=+
_shtab_tte_randomsequence__h_nargs=0
_shtab_tte_randomsequence___help_nargs=0
_shtab_tte_randomsequence___final_gradient_stops_nargs=+
_shtab_tte_randomsequence___final_gradient_steps_nargs=+
_shtab_tte_rings__h_nargs=0
_shtab_tte_rings___help_nargs=0
_shtab_tte_rings___ring_colors_nargs=+
_shtab_tte_rings___final_gradient_stops_nargs=+
_shtab_tte_rings___final_gradient_steps_nargs=+
_shtab_tte_scattered__h_nargs=0
_shtab_tte_scattered___help_nargs=0
_shtab_tte_scattered___final_gradient_stops_nargs=+
_shtab_tte_scattered___final_gradient_steps_nargs=+
_shtab_tte_slice__h_nargs=0
_shtab_tte_slice___help_nargs=0
_shtab_tte_slice___final_gradient_stops_nargs=+
_shtab_tte_slice___final_gradient_steps_nargs=+
_shtab_tte_slide__h_nargs=0
_shtab_tte_slide___help_nargs=0
_shtab_tte_slide___reverse_direction_nargs=0
_shtab_tte_slide___merge_nargs=0
_shtab_tte_slide___final_gradient_stops_nargs=+
_shtab_tte_slide___final_gradient_steps_nargs=+
_shtab_tte_smoke__h_nargs=0
_shtab_tte_smoke___help_nargs=0
_shtab_tte_smoke___smoke_symbols_nargs=+
_shtab_tte_smoke___smoke_gradient_stops_nargs=+
_shtab_tte_smoke___use_whole_canvas_nargs=0
_shtab_tte_smoke___final_gradient_stops_nargs=+
_shtab_tte_smoke___final_gradient_steps_nargs=+
_shtab_tte_spotlights__h_nargs=0
_shtab_tte_spotlights___help_nargs=0
_shtab_tte_spotlights___final_gradient_stops_nargs=+
_shtab_tte_spotlights___final_gradient_steps_nargs=+
_shtab_tte_spray__h_nargs=0
_shtab_tte_spray___help_nargs=0
_shtab_tte_spray___final_gradient_stops_nargs=+
_shtab_tte_spray___final_gradient_steps_nargs=+
_shtab_tte_swarm__h_nargs=0
_shtab_tte_swarm___help_nargs=0
_shtab_tte_swarm___base_color_nargs=+
_shtab_tte_swarm___final_gradient_stops_nargs=+
_shtab_tte_swarm___final_gradient_steps_nargs=+
_shtab_tte_sweep__h_nargs=0
_shtab_tte_sweep___help_nargs=0
_shtab_tte_sweep___sweep_symbols_nargs=+
_shtab_tte_sweep___final_gradient_stops_nargs=+
_shtab_tte_sweep___final_gradient_steps_nargs=+
_shtab_tte_synthgrid__h_nargs=0
_shtab_tte_synthgrid___help_nargs=0
_shtab_tte_synthgrid___grid_gradient_stops_nargs=+
_shtab_tte_synthgrid___grid_gradient_steps_nargs=+
_shtab_tte_synthgrid___text_gradient_stops_nargs=+
_shtab_tte_synthgrid___text_gradient_steps_nargs=+
_shtab_tte_synthgrid___text_generation_symbols_nargs=+
_shtab_tte_thunderstorm__h_nargs=0
_shtab_tte_thunderstorm___help_nargs=0
_shtab_tte_thunderstorm___raindrop_symbols_nargs=+
_shtab_tte_thunderstorm___spark_symbols_nargs=+
_shtab_tte_thunderstorm___final_gradient_stops_nargs=+
_shtab_tte_thunderstorm___final_gradient_steps_nargs=+
_shtab_tte_unstable__h_nargs=0
_shtab_tte_unstable___help_nargs=0
_shtab_tte_unstable___final_gradient_stops_nargs=+
_shtab_tte_unstable___final_gradient_steps_nargs=+
_shtab_tte_vhstape__h_nargs=0
_shtab_tte_vhstape___help_nargs=0
_shtab_tte_vhstape___glitch_line_colors_nargs=+
_shtab_tte_vhstape___glitch_wave_colors_nargs=+
_shtab_tte_vhstape___noise_colors_nargs=+
_shtab_tte_vhstape___final_gradient_stops_nargs=+
_shtab_tte_vhstape___final_gradient_steps_nargs=+
_shtab_tte_waves__h_nargs=0
_shtab_tte_waves___help_nargs=0
_shtab_tte_waves___wave_symbols_nargs=+
_shtab_tte_waves___wave_gradient_stops_nargs=+
_shtab_tte_waves___wave_gradient_steps_nargs=+
_shtab_tte_waves___final_gradient_stops_nargs=+
_shtab_tte_waves___final_gradient_steps_nargs=+
_shtab_tte_wipe__h_nargs=0
_shtab_tte_wipe___help_nargs=0
_shtab_tte_wipe___final_gradient_stops_nargs=+
_shtab_tte_wipe___final_gradient_steps_nargs=+


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_tte() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local previous_word="${COMP_WORDS[COMP_CWORD-1]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_tte
  local word_index=0
  local pos_only=0 # "--" delimiter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != "?" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_${completed_positional_actions}" true
      fi
    else
      pos_only=1 # "--" delimiter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  local completion
  if [[ $pos_only = 0 && "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    while IFS= read -r completion; do COMPREPLY+=("$completion"); done < <(
      compgen -W "${current_option_strings[*]}" -- "${completing_word}")
  elif [[ "${previous_word}" == ">" || "${previous_word}" == ">>" ||
          "${previous_word}" =~ ^[12]">" || "${previous_word}" =~ ^[12]">>" ]]; then
    # handle redirection operators
    while IFS= read -r completion; do COMPREPLY+=("$completion"); done < <(
      compgen -f -- "${completing_word}")
  else
    # use choices & compgen
    if [ -n "${current_action_compgen}" ]; then
      while IFS= read -r completion; do COMPREPLY+=("$completion"); done < <(
        "${current_action_compgen}" "${completing_word}")
    fi
    while IFS= read -r completion; do COMPREPLY+=("$completion"); done < <(
      compgen -W "${current_action_choices[*]}" -- "${completing_word}")
  fi

  return 0
}

complete -o filenames -F _shtab_tte tte
complete -o filenames -F _shtab_tte terminaltexteffects
